export { sqlInjection, commandInjection, codeInjection, nosqlInjection } from './injection.js';
export { xssReflected, xssDom } from './xss.js';
export { hardcodedCredentials, weakCryptography, insecureRandomness } from './auth.js';
export { pathTraversal, arbitraryFileAccess } from './path.js';
export { sensitiveDataExposure, insecureDeserialization } from './data.js';
export { securityMisconfiguration } from './config.js';
export { ssrf } from './ssrf.js';
export { insecureRegex } from './redos.js';
export { openRedirect } from './redirect.js';
export { jwtSignatureBypass } from './jwt.js';
export { xxe } from './xxe.js';
